### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by schuefab** [MohmmadAlharran/cinema4All#2]
In the following link you can see a prototyp of the homepage we created.
https://mockittapp.wondershare.com/app/961ecf98044b3d302ef3e7ba8cfce17b127bd690#screen=skj2sbc7si3182o

The font of the actual page will turn yellow when you are on this webpage.
With the arrows you can slide across all current movies, maybe we could make it with a slidebar or something else if you want.
When you click on the Title or the picture of the movies you will come to a specified website for every movie.
At the top left corner you can see the logo we created with svg. 
If there is something we should change let us know.

**Comment by MohmmadAlharran** [comment]
I like the prototyp very much .with the Arrows it will work too,but i think ComminSoon should not be designated as a landmark.

**Comment by schuefab** [comment]
Okay so we will change this on the website, thanks.
