### ISSUE TITLE
Copyright for images

### ISSUE THREAD

**Issue by ghost** [MohmmadAlharran/cinema4All#7]
Sorry if this question comes a little late. Under which license do you use the movie images you gave us? 

In the case you do not have the rights to use them should we change them to placeholder images?

**Comment by MohmmadAlharran** [comment]
no, we don't have a licence.but the website will not be published, so I think 
it does not matter.

**Comment by ghost** [comment]
The correct use of images is part of the grading. This includes copyright issues. I would recommend to change them.

**Comment by MohmmadAlharran** [comment]
it's up to u.

**Comment by ghost** [comment]
I have exchanged them just in case we have to. I will aks about that issue in the presentation.
